from aenum import Enum


class CodingType(Enum):
    MPEG2_VIDEO_PRIMARY_SECONDARY = 0x02,
    MPEG4_AVC_VIDEO_PRIMARY_SECONDARY = 0x1B,
    VC1_VIDEO_PRIMARY_SECONDARY = 0xEA,
    LPCM_AUDIO_PRIMARY = 0x80,
    AC3_AUDIO_PRIMARY = 0x81,
    DTS_AUDIO_PRIMARY = 0x82,
    TRUEHD_AUDIO_PRIMARY = 0x83,
    EAC3_AUDIO_PRIMARY = 0x84,
    DTS_HD_AUDIO_PRIMARY = 0x85,
    DTS_HD_XLL_AUDIO_PRIMARY = 0x86,
    EAC3_AUDIO_SECONDARY = 0xA1,
    DTS_HD_AUDIO_SECONDARY = 0xA2,
    PRESENTATION_GRAPHICS_SUBTITLES = 0x90,
    INTERACTIVE_GRAPHICS_MENU = 0x91,
    TEXT_SUBTITLES = 0x92,
